@urlPath=api/v1/comment

### Get all comments
GET {{baseUrl}}/{{urlPath}}/all-comments/648d96918519d4750290cfd0/1
Content-Type:application/json
withCredentials:true

### Add comment
POST {{baseUrl}}/{{urlPath}}/create-comment
Content-Type:application/json
withCredentials:true

{
  "postId": "648d96918519d4750290cfd0",
	"comment":"test1"
}

### Get comment
GET {{baseUrl}}/{{urlPath}}/647c6df9dc26ad6560886a47/647db337ff6b58ee43bca52b
Content-Type:application/json
withCredentials:true

### Get nameLists
GET {{baseUrl}}/{{urlPath}}/name-lists/647c6df9dc26ad6560886a47
Content-Type:application/json
withCredentials:true

### Update comment
PATCH {{baseUrl}}/{{urlPath}}/update-comment
Content-Type:application/json
withCredentials:true

{
  "postId": "648d96918519d4750290cfd0",
	"comment":"test3",
	"_Id":"6492a3b19e1e24501eefa014"
}

### Delete comment
DELETE {{baseUrl}}/{{urlPath}}/delete-comment
Content-Type:application/json
withCredentials:true

{
  "postId": "648d96918519d4750290cfd0",
	"comment":"test3",
	"_id":"6492a04a03e468f244f1db3a"
}
