@baseUrl = http://localhost:5000

@urlPath=api/v1/stock

@tickCartId = {{addTickCart.response.body.data.id}}
@tickId ={{addTick.response.body.data.tickData[0].id}}

### Load Historical Data
GET {{baseUrl}}/{{urlPath}}/load-stock
Content-Type:application/json
withCredentials:true

### Get Historical Data
GET {{baseUrl}}/{{urlPath}}/get-stock
Content-Type:application/json
withCredentials:true

### Get Last N Month Data
GET {{baseUrl}}/{{urlPath}}/get-stock/2
Content-Type:application/json
withCredentials:true

### Get filtered Data by price
GET {{baseUrl}}/{{urlPath}}/get-price?price=27200.24&date=2023-04-14T00:00:00.000Z&breakRatio=0.5&isAbove=false
Content-Type:application/json
withCredentials:true

### Get MA
GET {{baseUrl}}/{{urlPath}}/get-MA?selectedMonth=3&ma=30&candleRatio=0.25

Content-Type:application/json
withCredentials:true

### Get Candle direction
GET {{baseUrl}}/{{urlPath}}/get-candlestick?selectedMonth=3&upperShadowRatio=0.8&bodyRatio=&candlestickType=doji


Content-Type:application/json
withCredentials:true

### add price on the speific Tickid
POST {{baseUrl}}/{{urlPath}}/add-price
Content-Type:application/json
withCredentials:true

{
	"price":28000,
	"indicatorType":"price",
	"color":"#50b5ff",
	"breakRatio":0.75,
	"isAbove":false,
	"date":1681430400000,
	"TickId":"{{tickId}}"
}

### udpate price on the speific Tickid
PATCH {{baseUrl}}/{{urlPath}}/update-price
Content-Type:application/json
withCredentials:true

{
	"id":"939679ca-c835-46ba-a516-220012532b2c",
	"price":27000,
	"color":"#50b5ff",
	"breakRatio":0.75,
	"isAbove":false,
	"date":1681430400000
	}

### delete price on the speific Tickid
DELETE {{baseUrl}}/{{urlPath}}/delete-price
Content-Type:application/json
withCredentials:true

{
	"id":"939679ca-c835-46ba-a516-220012532b2c"
}

### add ma on the speific tick
POST {{baseUrl}}/{{urlPath}}/add-ma
Content-Type:application/json
withCredentials:true

{
	"ma":30,
	"indicatorType":"ma",
	"color":"#50b5ff",
	"breakRatio":0.75,
	"isAbove":false,
	"maBy":"close",
	"TickId":"{{tickId}}"
}


### get tick with user uid
# @name addTick
POST {{baseUrl}}/{{urlPath}}/get-tick
Content-Type:application/json
withCredentials:true

{
	"uId":"120212357708"
}


###add tick on the speific tickCart
# @name addTick
POST {{baseUrl}}/{{urlPath}}/add-tick
Content-Type:application/json
withCredentials:true

{
	"tick":"BTCUSDT",
	"open":100,
	"close":105,
	"low":98,
	"high":120,
	"TickCartId":"{{tickCartId}}"
}

###delete tick by tick name
POST {{baseUrl}}/{{urlPath}}/delete-tick
Content-Type:application/json
withCredentials:true

{
	"tick":"BTCUSDT",
	"TickCartId":"{{tickCartId}}"
}

###
# @name addTickCart
POST {{baseUrl}}/{{urlPath}}/add-tickCart
Content-Type:application/json
withCredentials:true

{
	"cartName":"crypto"
}

###delete tickCart on the speific user
POST {{baseUrl}}/{{urlPath}}/delete-tickCart
Content-Type:application/json
withCredentials:true

{
	"cartName":"crypto"
}
